### ISSUE TITLE
Overloaded getAuthorizationUrl is unnecessary

### ISSUE THREAD

**Issue by shadowhand** [lemonstand/oauth2-amazon#1]
It looks like `getAuthorizationUrl` is overloaded just to add the `sandbox` [parameter](https://github.com/lemonstand/oauth2-amazon/blob/dcf548c1c19543f5b2b27cc60f5a3a6afc74a105/src/Amazon.php#L69), which is not necessary at all:

``` php
public function getAuthorizationUrl($options = [])
{
    $url = parent::getAuthorizationUrl($options);
    if ($this->testMode) {
        $url .= '&sandbox=true';
    }
    return $url;
}
```

Would be the less intrusive way of adding the `sandbox` parameter.

**Comment by aperdomo** [comment]
@shadowhand,

Yes, yes it is.

See: https://github.com/lemonstand/oauth2-amazon/commit/48fde25
